module.exports = [
  {
    id: "operations",
    slug: "operations",
    tagKey: "ops",
    code: "OPS",
    letter: "O",
    title: "Operations & Admin",
    subtitle: "scheduling, process, systems",
    kicker: "Lens · Operations & Admin",
    headline: "Operations & Admin",
    dek: "COO-level ownership of scheduling, staffing, and process — the person who builds the system so nothing falls through the cracks, then documents it so it survives after she leaves the room.",
    pitch: "Bring me in and the chaos gets a system — one that keeps running after I leave the room.",
    offerPoints: [
      "A real operational audit, not a generic checklist — I find what's actually breaking",
      "SOPs and job aids your team can follow correctly under pressure",
      "Scheduling, staffing, and vendor coordination handled end-to-end",
      "Systems built to outlast me, so nothing depends on tribal knowledge"
    ],
    stats: [
      { name: "Operations Leadership", pct: 90 },
      { name: "Documentation & SOPs", pct: 95 },
      { name: "Process Design", pct: 88 },
      { name: "Vendor & Stakeholder Coordination", pct: 80 }
    ],
    flagship: {
      title: "Beauties of the Beasts — where it's headed",
      labels: ["Right now", "Next chapter", "Why it matters"],
      problem: "Two programs today — reptile rescue and Bunch a Bull, a breed-specific bulldog program — running out of a home in Yuma. Scope has stayed narrow on purpose, but a home has a ceiling, and we've been up against it for a while.",
      approach: "Working to secure a dedicated facility — more intake capacity, real quarantine space at scale, and the room to say yes to species and situations we currently have to turn away. Not promised on a timeline, but it's the single biggest thing standing between where we are and where we want to be.",
      result: "When Yuma recently lost part of its capacity for cats as a local shelter closed its cat program, that's exactly the kind of gap a facility lets us respond to. Behind it: general dog & cat intake, expanded reptile capacity, a larger bulldog program, community education, veterans support, a special needs program, safe haven fostering for domestic violence survivors, animal-assisted therapy, and a low-cost vet clinic.",
      stats: [{ k: "2", v: "programs today" }, { k: "9", v: "programs planned" }, { k: "2023", v: "rescue founded" }, { k: "1", v: "facility away" }],
      link: { label: "Read the full vision", href: "https://yumareptiles.com/vision/" }
    },
    ctaPrimary: { label: "Email me about a role", href: "mailto:bowman.shiann@gmail.com" },
    ctaSecondary: { label: "Call 928-916-3711", href: "tel:9289163711" },
    ctaNote: "Open to operations, scheduling, and admin roles where building the right process matters.",
    fossilSpecies: "Ankylosaurus",
    fossilImage: "/assets/images/field-record/fossils/ops-ankylosaurus.jpg",
    fossilBlurb: "Armored and immovable — built to keep the whole operation standing no matter what hits it.",
    fossilCredit: "Photo: Tim Evanson, CC BY-SA 2.0 (cropped)",
    fossilCreditUrl: "https://commons.wikimedia.org/wiki/File:Ankylosaur_head_-_cast_-_Custer_County_Montana_-_Museum_of_the_Rockies_-_2013-07-08.jpg"
  },
  {
    id: "caregiving",
    slug: "caregiving",
    tagKey: "care",
    code: "CARE",
    letter: "C",
    title: "Healthcare & Caregiving",
    subtitle: "senior, veteran & special-needs care",
    kicker: "Lens · Healthcare & Caregiving",
    headline: "Senior, Veteran & Special-Needs Care",
    dek: "5+ years of direct client care for veterans, seniors, and clients with autism and cerebral palsy — plus the operational eye to fix the system around the care.",
    pitch: "One-on-one care from someone who treats your family member like family — not a task on a shift list.",
    offerPoints: [
      "Individualized care plans built around the actual person, not a template",
      "Direct, proactive communication with doctors, family, and other providers",
      "Calm, trained composure if a medical or behavioral situation goes sideways",
      "Real experience with seniors, veterans, autism, and cerebral palsy — not just a certificate"
    ],
    stats: [
      { name: "Direct Client Care", pct: 95 },
      { name: "Care Plan Documentation", pct: 90 },
      { name: "Crisis Composure", pct: 85 },
      { name: "Family & Provider Communication", pct: 88 }
    ],
    testimonial: "care",
    ctaPrimary: { label: "Email me about a caregiving role", href: "mailto:bowman.shiann@gmail.com" },
    ctaSecondary: { label: "Call 928-916-3711", href: "tel:9289163711" },
    ctaNote: "Currently a caregiver with Cornerstone Caregiving and available for additional direct-care clients — reach out directly to talk specifics.",
    fossilSpecies: "Maiasaura",
    fossilImage: "/assets/images/field-record/fossils/care-maiasaura.jpg",
    fossilBlurb: "The name literally means “good mother lizard” — famous for nesting in colonies and raising her hatchlings with real care.",
    fossilCredit: "Photo: Vladimír Socha, CC BY-SA 4.0 (cropped)",
    fossilCreditUrl: "https://commons.wikimedia.org/wiki/File:Maiasaura_skeleton.jpg",
    fossilEgg: "I once got to rehab and bottle-feed an orphaned squirrel. Zero regrets."
  },
  {
    id: "training",
    slug: "training",
    tagKey: "train",
    code: "TRN",
    letter: "T",
    title: "Training & Documentation",
    subtitle: "SOPs, onboarding, job aids",
    kicker: "Lens · Training & Documentation",
    headline: "Training & Documentation",
    dek: "SOPs, onboarding guides, and job aids built for real teams — five years doing it professionally at scale, plus three volunteer programs still running on the same discipline today.",
    pitch: "Documentation people actually use — because it's written for someone stressed and in a hurry, not for a binder nobody opens.",
    offerPoints: [
      "SOPs and onboarding guides tested on someone who's never done the task before they ship",
      "Job aids built for the worst day on the floor, not the demo",
      "Full training program design — not just a slide deck and a hope",
      "Systems that keep new hires productive whether or not I'm in the room"
    ],
    stats: [
      { name: "Curriculum & SOP Design", pct: 95 },
      { name: "Onboarding Program Design", pct: 92 },
      { name: "Adult Learning Facilitation", pct: 85 },
      { name: "Documentation Systems", pct: 90 }
    ],
    ctaPrimary: { label: "Email me about a role", href: "mailto:bowman.shiann@gmail.com" },
    ctaSecondary: { label: "Call 928-916-3711", href: "tel:9289163711" },
    ctaNote: "Open to training, L&D, and documentation roles — remote or Yuma, AZ.",
    fossilSpecies: "Troodon",
    fossilImage: "/assets/images/field-record/fossils/train-troodon.jpg",
    fossilBlurb: "Widely considered the smartest dinosaur going, with the largest brain-to-body ratio of the bunch.",
    fossilCredit: "Photo: Montanoceratops, public domain (cropped)",
    fossilCreditUrl: "https://commons.wikimedia.org/wiki/File:Troodon_MOR_full.png"
  },
  {
    id: "webdesign",
    slug: "webdesign",
    tagKey: "build",
    code: "WEB",
    letter: "B",
    title: "Web Design & Builder",
    subtitle: "sites, apps, shipped software",
    kicker: "Lens · Web Design & Builder",
    headline: "Web Design & App Development",
    dek: "Not just requirements — shipped software. A 60-screen operations platform, live client websites, and a running studio (Avoria) built on hand-coded, no-subscription tech: one flat price, and no invoice until the client approves a working draft.",
    pitch: "A hand-coded site or app at one flat price — and you don't pay a cent until you approve a working draft.",
    offerPoints: [
      "No subscriptions, no page-builder lock-in, $0/month hosting",
      "A real working draft before any invoice exists — not a mockup, not a promise",
      "50+ clients, 5.0 average rating, zero refund requests ever",
      "Full-stack capability on tap if you need more than a marketing site"
    ],
    stats: [
      { name: "Front-end Build (HTML/CSS/JS)", pct: 82 },
      { name: "Full-stack Product Design", pct: 75 },
      { name: "Client Delivery Speed", pct: 90 },
      { name: "Systems Thinking", pct: 85 }
    ],
    testimonial: "build",
    flagship: {
      title: "SanctuaryBase — the flagship build",
      problem: "A real rescue was running volunteer shifts, medical records, and donor tracking across group chats and spreadsheets. Things fell through constantly, and no one could see the whole picture at once.",
      approach: "Designed and hand-built a 60-screen operations platform from scratch — 16-tab animal records (health, meds, vaccines, behavior, SOS alerts), shift scheduling, a full donor CRM, a vet triage hub with an AI health assistant, and grant/finance tracking, all behind role-based access.",
      result: "Shipped as an offline-capable PWA and running in daily use today at Saint Francis Rescue & Sanctuary of Yuma — not a prototype, the system staff actually work from.",
      stats: [{ k: "60", v: "screens shipped" }, { k: "16", v: "tabs per record" }, { k: "PWA", v: "offline-capable" }, { k: "Solo", v: "design + build" }]
    },
    ctaPrimary: { label: "Start a project at Avoria →", href: "https://avoria-premium-agency.pages.dev" },
    ctaSecondary: { label: "Email me about a role", href: "mailto:bowman.shiann@gmail.com" },
    ctaNote: "Hiring for a technical/product role? Email me directly. Need a site or app built? Start a project through Avoria — nothing's owed until you approve the draft.",
    fossilSpecies: "Deinonychus",
    fossilImage: "/assets/images/field-record/fossils/build-deinonychus.jpg",
    fossilBlurb: "Fast, sharp-clawed, and built to execute — the velociraptor's bigger, smarter cousin.",
    fossilCredit: "Photo: Jonathan Chen, CC BY-SA 4.0 (cropped)",
    fossilCreditUrl: "https://commons.wikimedia.org/wiki/File:Deinonychus_FMNH.jpg"
  },
  {
    id: "marketing",
    slug: "marketing",
    tagKey: "mkt",
    code: "MKT",
    letter: "M",
    title: "Marketing & Content",
    subtitle: "campaigns, copy, community",
    kicker: "Lens · Marketing & Content",
    headline: "Marketing & Content",
    dek: "Ran the full content and growth function for a 501(c)(3) — copy, campaigns, community, and paid strategy — after four years freelancing the same for other clients.",
    pitch: "Content and campaigns run by someone who's already grown a real organization from the ground up — not just studied how.",
    offerPoints: [
      "Copywriting and brand voice that doesn't read like a template",
      "Campaign execution across email, social, and paid — not just one channel",
      "Community growth strategy, not a content calendar on autopilot",
      "Performance tracking that actually changes what happens next"
    ],
    stats: [
      { name: "Copywriting & Content", pct: 78 },
      { name: "Campaign Execution", pct: 75 },
      { name: "Community & Audience Growth", pct: 80 },
      { name: "Brand Voice Consistency", pct: 82 }
    ],
    ctaPrimary: { label: "Email me about a role", href: "mailto:bowman.shiann@gmail.com" },
    ctaSecondary: { label: "Call 928-916-3711", href: "tel:9289163711" },
    ctaNote: "Open to marketing, content, and communications roles — remote or Yuma, AZ.",
    fossilSpecies: "Parasaurolophus",
    fossilImage: "/assets/images/field-record/fossils/mkt-parasaurolophus.jpg",
    fossilBlurb: "Grew a hollow head crest that worked like a built-in trombone, broadcasting calls for miles.",
    fossilCredit: "Photo: Zissoudisctrucker, CC BY-SA 4.0 (cropped)",
    fossilCreditUrl: "https://commons.wikimedia.org/wiki/File:FMNH_Parasaurolophus_fossil.jpg",
    fossilEgg: "Business hero: Ryan Serhant. Study the hustle, not just the highlight reel."
  },
  {
    id: "crisis",
    slug: "crisis",
    tagKey: "crisis",
    code: "CRS",
    letter: "X",
    title: "Crisis & Support",
    subtitle: "live calls, first-responder coordination",
    kicker: "Lens · Crisis & Support",
    headline: "Crisis Response & Support",
    dek: "Three years on live emergency calls at Uber, coordinating with first responders under time pressure, with full compliance documentation on every case.",
    pitch: "Composure on the worst call of someone's day, with the documentation to back it up afterward.",
    offerPoints: [
      "Live incident handling under real time pressure, not simulated scenarios",
      "Direct coordination with first responders and other agencies as it's happening",
      "Full compliance documentation on every case, every time — no gaps",
      "Trauma-informed communication that de-escalates instead of making things worse"
    ],
    stats: [
      { name: "Composure Under Pressure", pct: 92 },
      { name: "Live Call Handling", pct: 88 },
      { name: "Compliance Documentation", pct: 85 },
      { name: "First-Responder Coordination", pct: 80 }
    ],
    ctaPrimary: { label: "Email me about a role", href: "mailto:bowman.shiann@gmail.com" },
    ctaSecondary: { label: "Call 928-916-3711", href: "tel:9289163711" },
    ctaNote: "Open to crisis response, trust & safety, or high-pressure support roles.",
    fossilSpecies: "Tyrannosaurus rex",
    fossilImage: "/assets/images/field-record/fossils/crisis-tyrannosaurus-rex.jpg",
    fossilBlurb: "The one you call when it's serious — apex responder, handled the biggest problems in the room.",
    fossilCredit: "Photo: ScottRobertAnselmo, CC BY-SA 3.0 (cropped)",
    fossilCreditUrl: "https://commons.wikimedia.org/wiki/File:Tyrannosaurus_Rex_Holotype.jpg"
  },
  {
    id: "retail",
    slug: "retail",
    tagKey: "retail",
    code: "RTL",
    letter: "R",
    title: "Retail & Customer Service",
    subtitle: "front-of-house, reliability",
    kicker: "Lens · Retail & Customer Service",
    headline: "Retail & Customer Service",
    dek: "No formal retail title on the resume — but the job is the same skill set I've run for a decade: stay composed with a difficult person, keep records accurate under pressure, show up every shift, and make people feel taken care of. I built my own booking, quoting, and scheduling systems from scratch, so a POS or scheduling tool won't slow me down for long.",
    pitch: "The shift that never has to be double-checked — reliable, composed, and ready to start now.",
    offerPoints: [
      "Zero-drama handling of difficult customers, every time, not just on a good day",
      "Accurate cash handling and recordkeeping under pressure",
      "Immediate availability for interviews in Yuma, AZ",
      "Comfortable picking up any POS or scheduling system fast — I've built my own"
    ],
    stats: [
      { name: "Customer-Facing Composure", pct: 90 },
      { name: "Reliability & Punctuality", pct: 95 },
      { name: "Cash & Records Accuracy", pct: 88 },
      { name: "Fast-Paced Multitasking", pct: 85 }
    ],
    ctaPrimary: { label: "Email me about a role", href: "mailto:bowman.shiann@gmail.com" },
    ctaSecondary: { label: "Call 928-916-3711", href: "tel:9289163711" },
    ctaNote: "Open to retail, front-of-house, and customer service roles in Yuma, AZ — available for interviews immediately.",
    fossilSpecies: "Triceratops",
    fossilImage: "/assets/images/field-record/fossils/retail-triceratops.jpg",
    fossilBlurb: "Held the front line of the herd, unbothered, facing every threat head-on.",
    fossilCredit: "Photo: Allie Caulfield / MathKnight, CC BY-SA 3.0 (cropped)",
    fossilCreditUrl: "https://commons.wikimedia.org/wiki/File:LA-Triceratops_mount-2.jpg",
    fossilEgg: "My sales skills are unmatched. Put me in front of a customer and find out."
  },
  {
    id: "cleaning",
    slug: "cleaning",
    tagKey: "clean",
    code: "CLN",
    letter: "H",
    title: "Home Cleaning",
    subtitle: "deep, standard & move-out",
    kicker: "Lens · Home Cleaning",
    headline: "Home Cleaning",
    dek: "Flat-rate house cleaning through Clean Convictions — regular cleaning from $89, deep cleans from $179, move-in/move-out from $199, plus office & commercial service. Published pricing, pet-safe products, a military/veteran discount, and a simple guarantee: miss a spot, tell us within 24 hours, and we re-clean it free.",
    pitch: "A flat-rate clean with a real guarantee — miss a spot, tell us within 24 hours, and we're back free.",
    offerPoints: [
      "Published flat-rate pricing — no in-home estimate, no surprise invoice",
      "Pet-safe products and a military/veteran discount",
      "Regular, deep, and move-in/move-out cleans, plus office & commercial",
      "A free instant quote online in about 60 seconds, no sales call required"
    ],
    stats: [
      { name: "Attention to Detail", pct: 95 },
      { name: "Reliability & Consistency", pct: 96 },
      { name: "Client Trust & Retention", pct: 92 },
      { name: "Efficiency & Time Management", pct: 85 }
    ],
    ctaPrimary: { label: "Get a flat-rate quote →", href: "https://cleanconvictions.com" },
    ctaSecondary: { label: "Call/text 928-298-5509", href: "tel:9282985509" },
    ctaNote: "Free flat-rate quote in about 60 seconds online — instant pricing, no sales call, no waiting.",
    fossilSpecies: "Stegosaurus",
    fossilImage: "/assets/images/field-record/fossils/clean-stegosaurus.jpg",
    fossilBlurb: "Armor-plated and meticulous — even 150 million years ago, upkeep mattered.",
    fossilCredit: "Photo: Maidment et al. & Natural History Museum, London, CC BY 4.0 (cropped)",
    fossilCreditUrl: "https://commons.wikimedia.org/wiki/File:Journal.pone.0138352.g001A.jpg"
  }
];
